connect/urls.py
# pylint: disable=invalid-name

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView

from social import views

urlpatterns = [
    path('', include('social.urls')),
    path('admin/', admin.site.urls),
    path('social/', RedirectView.as_view(url='')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup', views.signup, name='signup'),
    path('posts', views.UserPostListView.as_view(), name='posts-list'),
    path('api/social/', include('social.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/api/urls.py
# pylint: disable=invalid-name
from django.urls import path

from social.api import views


app_name = 'social-api'

urlpatterns = [
    path('users_all/', views.ListUserProfilesView.as_view(), name='users-all'),
]

social/urls.py
# pylint: disable=invalid-name
from django.urls import path

from social import views


app_name = 'social'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/<username>/', views.profile, name='profile'),
]

social/models.py
from datetime import date

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils import timezone
from django.utils.text import Truncator

from phonenumber_field.modelfields import PhoneNumberField


class UserProfile(AbstractUser):
    USERPROFILE_BIO_MAX_LENGTH = 400
    bio = models.TextField(
        max_length=USERPROFILE_BIO_MAX_LENGTH,
        help_text="You bio here!"
    )
    phone_number = PhoneNumberField()
    website = models.URLField(max_length=250)
    photo = models.ImageField(
        upload_to='upload/profile/',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ["date_joined"]

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('polls:profile', kwargs={'username': self.username})

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def followers_count(self):
        return Connection.objects.filter(following=self).count()

    @property
    def following_count(self):
        return Connection.objects.filter(follower=self).count()

    def follow_user(self, userprofile, follow: bool):
        if follow:
            Connection.objects.get_or_create(
                follower=self, following=userprofile)
        else:
            Connection.objects.filter(
                follower=self, following=userprofile).delete()


def get_active_user(username: str):
    try:
        user = UserProfile.objects.get(username=username)
    except UserProfile.DoesNotExist:
        return None
    if not user.is_active:
        return None
    return user


class Connection(models.Model):
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='follower',
        on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='following',
        on_delete=models.CASCADE
    )
    date_created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["date_created"]

    def __str__(self):
        return f"{self.follower} : {self.following}"


class UserPostManager(models.Manager):
    def create_userpost(self, user_profile, text, **extra_fields):
        if not text:
            raise ValueError("User post can't be empty")
        userpost = self.model(user_profile=user_profile,
                              text=text, **extra_fields)
        userpost.save()
        return userpost


class UserPost(models.Model):
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        blank=True
    )
    date_posted = models.DateField(default=date.today)
    date_updated = models.DateField(default=date.today)
    likes = models.IntegerField(default=0)
    PUBLIC = 1
    PRIVATE = 2
    PRIVACY_CHOICES = (
        (PUBLIC, 'Public'),
        (PRIVATE, 'Private'),
    )
    privacy = models.PositiveSmallIntegerField(
        default=PUBLIC,
        choices=PRIVACY_CHOICES
    )

    USERPOST_TEXT_MAX_LENGTH = 1000
    text = models.TextField(
        max_length=USERPOST_TEXT_MAX_LENGTH,
        help_text="Your post here!"
    )

    objects = UserPostManager()

    class Meta:
        ordering = ["date_updated"]

    def get_number_of_likes(self):
        return self.like_set.count()

    def __str__(self):
        return f"Posted on {self.date_posted} : {Truncator(self.text).chars(50)}"


class Comment(models.Model):
    user_post = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    commenter = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        blank=True
    )
    text = models.CharField(max_length=100)
    date_posted = models.DateField(default=date.today)

    def __str__(self):
        return f"Posted on {self.date_posted}. Comment: {self.text}"


class Like(models.Model):
    user_post = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("user_post", "user_profile")

social/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from social.models import UserProfile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=39, required=False,
                                 help_text="Optional. Enter First Name")
    last_name = forms.CharField(max_length=39, required=False,
                                help_text="Optional. Enter last Name")
    email = forms.CharField(max_length=254,
                            help_text="Required. Enter your email")
    website = forms.URLField(initial='http://', label="Website")
    photo = forms.ImageField(label="Upload your profile photo")

    bio = forms.CharField(
        max_length=UserProfile.USERPROFILE_BIO_MAX_LENGTH,
        required=False,
        help_text="Optional. Enter your bio.",
        widget=forms.Textarea)

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'website',
            'bio',
        )

social/api/views.py
from rest_framework import generics

from social.api.serializer import UserProfileSerializer
from social.models import (
    UserProfile,
)


class ListUserProfilesView(generics.ListAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer

social/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import (
    HttpRequest, HttpResponse
)
from django.shortcuts import redirect, render
from django.views import generic

from social.forms import SignUpForm
from social.models import (
    UserPost, get_active_user,
)


def signup(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        return redirect('social:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('social:home')
    else:
        form = SignUpForm()

    return render(request, 'registration/signup.html', {'form': form})


def home(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        return redirect('posts-list')

    return render(
        request,
        'home.html',
    )


class UserPostListView(LoginRequiredMixin, generic.ListView):
    model = UserPost
    paginate_by = 10


@login_required
def profile_settings():
    pass


def profile(request: HttpRequest, username: str) -> HttpResponse:
    user = get_active_user(username)
    if not user:
        return redirect('social:home')

    context = {
        'user': user,
    }
    return render(request, 'profile.html', context)

social/templates/base_generic.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Let's connect!</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light connect-bg-nav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'social:home' %}">
                <h1>Connect</h1>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link active" href="{% url 'social:home' %}">Home</a>
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'social:profile' user.get_username %}">
                        User: {{ user.get_username }}
                    </a>
                    <a class="nav-item nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'signup'%}?next={{request.path}}">Signup</a>
                    <a class="nav-item nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container py-3 pl-5">
        <div class="row">
            <div class="col-sm-10 ">
                {% block content %}
                {% endblock content%}
                {% block pagination %}
                {% include "pagination.html" %}
                {% endblock pagination %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

social/templates/bs4_form.html
{% load widget_tweaks %}
<form method="post">
    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}

            {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">
        {% if submit_button_text %}
            {{ submit_button_text }}
        {% else %}
            Submit
        {% endif %}
    </button>
</form>

social/templates/home.html
{% extends "base_generic.html" %}

{% block content %}
<p>Global social platform</p>
{% endblock %}

social/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<p>Global social platform</p>
{% endblock %}

social/templates/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}

        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% else %}
            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="page-link">
                Next
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Next</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}

social/templates/profile.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <section class="row">
        <div class="col-4 profile-box">
            <div class="profile-photo">
                {% if user.photo %}
                <img src="{{ user.photo.url }}" alt="Profile Picture" class="img-thumbnail rounded-circle">
                {% else %}
                {% load static %}
                <img src="{% static 'images/profile_placeholder.jpg' %}" alt="Default image" class="img-thumbnail rounded-circle">
                {% endif %}
            </div>
        </div>
        <section class="col">
            <div>
                <h1 class="d-inline username">{{ user.username}}</h1>
                <button type="button" class="btn btn-outline-primary">
                    Follow
                </button>
            </div>
            <ul class="list-inline">
                <li class="list-inline-item posts-count">
                    Posts <span class="posts-count-numbers">12</span>
                </li>
                <li class="list-inline-item followers-count">
                    Followers
                    <a href="#">
                        <span class="followers-count-numbers">{{ user.followers_count }}</span>
                    </a>
                </li>
                <li class="list-inline-item following-count">
                    Following
                    <a href="#">
                        <span class="following-count-number">{{ user.following_count }}</span>
                    </a>
                </li>
            </ul>
            <div class="user-fullname">
                <strong>
                    <span class="first_name">{{ user.first_name }}</span>
                    <span class="last_name">{{ user.last_name }}</span>
                </strong>
            </div>
            <a href="{{ user.website }}" target="_blank">{{ user.website }}</a>
            <p class="bio">{{ user.bio }}</p>
        </section>
    </section>
</div>
{% endblock content %}

social/templates/social/userpost_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Recent posts</h1>
    {% if userpost_list %}
    <ul>
        {% for post in userpost_list %}
        <li>
            {{ post.text }}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No post available.</p>
    {% endif %}
{% endblock %}